"""add category model

Revision ID: fa55dd33c21f
Revises: b6229c565f38
Create Date: 2022-01-15 21:09:17.132576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa55dd33c21f'
down_revision = 'b6229c565f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.add_column('advertisment', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_advertisment_category_category_id', 'advertisment', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_advertisment_category_category_id', 'advertisment', type_='foreignkey')
    op.drop_column('advertisment', 'category_id')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
